
package com.training.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TravelService", targetNamespace = "http://ifaces.training.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TravelService {


    /**
     * 
     * @param destination
     * @return
     *     returns com.training.clients.StringArray
     */
    @WebMethod
    @WebResult(name = "locations", partName = "locations")
    @Action(input = "http://ifaces.training.com/TravelService/weekEndPlannerRequest", output = "http://ifaces.training.com/TravelService/weekEndPlannerResponse")
    public StringArray weekEndPlanner(
        @WebParam(name = "destination", partName = "destination")
        String destination);

    /**
     * 
     * @param destination
     * @return
     *     returns com.training.clients.StringArray
     */
    @WebMethod
    @WebResult(name = "summer_locations", partName = "summer_locations")
    @Action(input = "http://ifaces.training.com/TravelService/summerHolidayRequest", output = "http://ifaces.training.com/TravelService/summerHolidayResponse")
    public StringArray summerHoliday(
        @WebParam(name = "destination", partName = "destination")
        String destination);

    /**
     * 
     * @param customerType
     * @return
     *     returns com.training.clients.TravelAgent
     */
    @WebMethod
    @WebResult(name = "Suggested_Travel_Agent", partName = "Suggested_Travel_Agent")
    @Action(input = "http://ifaces.training.com/TravelService/getTravelAgentRequest", output = "http://ifaces.training.com/TravelService/getTravelAgentResponse")
    public TravelAgent getTravelAgent(
        @WebParam(name = "customerType", partName = "customerType")
        String customerType);

}
