
package com.training.clients;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TravelServiceImplService", targetNamespace = "http://services.training.com/", wsdlLocation = "http://localhost:2020/jaxws/travel?wsdl")
public class TravelServiceImplService
    extends Service
{

    private final static URL TRAVELSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRAVELSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TRAVELSERVICEIMPLSERVICE_QNAME = new QName("http://services.training.com/", "TravelServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2020/jaxws/travel?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRAVELSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TRAVELSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TravelServiceImplService() {
        super(__getWsdlLocation(), TRAVELSERVICEIMPLSERVICE_QNAME);
    }

    public TravelServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRAVELSERVICEIMPLSERVICE_QNAME, features);
    }

    public TravelServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TRAVELSERVICEIMPLSERVICE_QNAME);
    }

    public TravelServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRAVELSERVICEIMPLSERVICE_QNAME, features);
    }

    public TravelServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TravelServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TravelService
     */
    @WebEndpoint(name = "TravelServiceImplPort")
    public TravelService getTravelServiceImplPort() {
        return super.getPort(new QName("http://services.training.com/", "TravelServiceImplPort"), TravelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TravelService
     */
    @WebEndpoint(name = "TravelServiceImplPort")
    public TravelService getTravelServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.training.com/", "TravelServiceImplPort"), TravelService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAVELSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TRAVELSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TRAVELSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
